dox/urls.py
from django.urls import path

from . import views

app_name = 'dox'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:topic_id>/', views.detail, name='detail'),
    path('app_dox', views.per_app_docs, name='per_app_dox'),
    path('app_dox_detail/<int:topic_id>/', views.sv_detail, name='app_dox_detail'),
]

lasttime/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('subadd/', include('subadd.urls')),
    path('recadm/', include('recadm.urls')),
    path('dataview/', include('dataview.urls')),
    # path('home/', include('home.urls')),
    path('', include('home.urls')),
    path('dox/', include('dox.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
]

subadd/urls.py
from django.urls import path

from . import views

app_name = "subadd"
urlpatterns = [
    path('', views.index, name='index'),
    path('add', views.add, name='add'),
    path('addentry', views.addentry, name='addentry'),
    path('<int:substance_id>/', views.detail, name='detail'),
    path('add_class', views.add_sub_class, name='add_sub_class'),
    path('class_details/<int:class_id>/', views.sub_class_details, name='sub_class_details'),
    path('edit', views.edit_sub, name='edit_sub'),
    path('edited_sub/<int:sub_id>/', views.edited_sub, name='edited_sub'),
]

subadd/models.py
from django.db import models


class DosageUnit(models.Model):
    """
    Contains all of the possible dosing units for the different available
    substances.
    """

    abbreviation = models.CharField("unit abbreviation", max_length=5)
    description = models.CharField("unit description", max_length=20)

    def __str__(self):
        return self.abbreviation

subadd/forms.py
from django.db import models
from django import forms
from django.forms import ModelForm

from .models import DosageUnit


class Substance(models.Model):
    """
    Class holds the details for each particular substance added to the
    available druggies database.

    TODO: add the ability to pick between the appropriate dosage Enums
    """

    common_name = models.CharField(max_length=40, unique=True)
    sci_name = models.CharField(max_length=60, unique=True)
    sub_class = models.ForeignKey('subadd.SubstanceClass', on_delete=models.CASCADE, null=True, default=None)
    half_life = models.DecimalField(max_digits=7, decimal_places=3)
    active_half_life = models.DecimalField(max_digits=7, decimal_places=3)
    lipid_solubility = models.BooleanField(default=False)
    units = models.CharField(max_length=5)

    def __str__(self):
        # return_text = self.common_name + " (" + self.sci_name + "): half-life: " + str(self.half_life) + \
        #     "; detectable half-life: " + str(self.active_half_life)
        #
        # if self.lipid_solubility:
        #     return_text += " - lipid soluble"
        #
        # return return_text
        return self.common_name + " (" + self.sci_name + ")"


class SubstanceForm(ModelForm):
    """
    Derived from the substance class, this holds the fields that need to be
    filled out by the user in order to record a new substance's relevant
    characteristics for later administration records.
    """

    units = forms.ModelChoiceField(DosageUnit.objects.all(), empty_label="-Dosage Units-", to_field_name="abbreviation")

    class Meta:
        model = Substance
        fields = ['common_name', 'sci_name', 'half_life', 'active_half_life', 'lipid_solubility']


class SubstanceClass(models.Model):
    """
    Class holds the details for substance classes.
    """

    name = models.CharField(max_length=25, unique=True)
    desc = models.CharField(max_length=160)

    def __str__(self):
        return self.name


class SubstanceClassForm(ModelForm):
    """
    Pretty much goes without saying at this point, don't you agree?
    """

    class Meta:
        model = SubstanceClass
        fields = ['name', 'desc']

subadd/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator

from lasttime.myglobals import MiscMethods

from .forms import Substance, SubstanceClass, SubstanceClassForm, SubstanceForm


@login_required
def index(request):
    """
    View provides a listing of all substances in the database; passes the
    information on to the index template for rendering.

    :param request:
    :return:
    """

    all_subs = Substance.objects.all()
    paginator = Paginator(all_subs, 15)  # 15 admins per page

    page = request.GET.get('page')
    subs = paginator.get_page(page)

    context = {
        'all_subs': subs,
    }

    return render(request, 'subadd/index.html', MiscMethods.add_pagination_info(MiscMethods.add_header_info(context),
                                                                                subs))


@login_required
def add(request):
    """
    View provides an empty form with the relevant fields (see forms.py) needing
    to be filled out by the user in order to record a new substance.  Passes
    the form off to add.html for rendering.

    :param request:
    :return:
    """

    add_sub_form = SubstanceForm()

    return render(request, 'subadd/add.html', MiscMethods.add_header_info({'substance': None,
                                                                           'add_sub_form': add_sub_form}))


@login_required
def addentry(request):
    """
    Another version of the above substance data entry form, this one is for
    usage when there was an error in validation or submission and processing
    of the previous form; this one comes pre-filled with whatever data the
    user had previously submitted.  Hands things off to addentry template,
    if there is an issue in saving the database record from the previous
    entry, otherwise it stuffs everything in the database where it needs to
    go and sends the user back to the index template in order to see the
    substances summary so that they can verify that their addition has been
    added.

    :param request:
    :return:
    """

    try:
        substance = Substance(common_name=request.POST['common_name'],
                              sci_name=request.POST['sci_name'],
                              half_life=request.POST['half_life'],
                              active_half_life=request.POST['active_half_life'],
                              lipid_solubility=request.POST.get('lipid_solubility', False),
                              units=request.POST['units'])

        # we'll need to do validation here, of course

    except:
        context = {}
        context['error_message'] = "Please navigate to addentry (here) only from the links."

        return render(request, 'subadd/add.html', MiscMethods.add_header_info(context))


    try:
        if substance.lipid_solubility != False:
            substance.lipid_solubility = True

        substance.save()
    except Exception as ex:
        context = {}
        context['error_message'] = "Unable to save record to database (" + str(ex) + ")!"
        context['substance'] = substance

        return render(request, 'subadd/add.html', MiscMethods.add_header_info(context))

    return render(request, 'subadd/index.html', MiscMethods.add_header_info({'all_subs': Substance.objects.all()}))


@login_required
def edit_sub(request):
    """
    View provides the capability to edit a substance's details.

    :param request:
    :param substance_id:
    :return:
    """

    context = {}

    if request.method == 'POST':
        # print(request.POST['sub_to_edit'])
        try:
            substance_to_edit = Substance.objects.get(id=request.POST['sub_to_edit'])     # SubstanceForm

        except Exception as ex:
            context['substances'] = Substance.objects.all()
            context['error_message'] = "No substance selected for editing!"

            return render(request, 'subadd/edit_sub.html', MiscMethods.add_header_info(context))

        # substance_form = substance
        context['substance_form'] = SubstanceForm(instance=substance_to_edit)
        context['sub_id'] = request.POST['sub_to_edit']

        return render(request, 'subadd/edit_sub.html', MiscMethods.add_header_info(context))

    else:
        context['substances'] = Substance.objects.all()

        return render(request, 'subadd/edit_sub.html', MiscMethods.add_header_info(context))


@login_required
def edited_sub(request, sub_id):
    """
    View saves the [presumably] changed information from the previous edit_sub
    view's Substance record.

    :param request:
    :param sub_id:
    :return:
    """

    context = {}

    edited_substance = Substance.objects.get(id=sub_id)

    # print(str(edited_substance))
    # print("\n---\n")

    edited_substance.common_name = request.POST['common_name']
    edited_substance.sci_name = request.POST['sci_name']
    edited_substance.half_life = request.POST['half_life']
    edited_substance.active_half_life = request.POST['active_half_life']
    # edited_substance.lipid_solubility = request.POST['lipid_solubility']
    edited_substance.lipid_solubility = request.POST.get('lipid_solubility', False)
    # don't forget to check the measurement value, detc

    # if edited_substance.lipid_solubility != False:
    #     edited_substance.lipid_solubility = True

    context['edited_substance'] = edited_substance

    try:
        edited_substance.save()

        context['user_message'] = "Saved this record for " + edited_substance.common_name + "."

    except Exception as ex:
        context['error_message'] = "Unable to save record for " + edited_substance.common_name + ": " + str(ex)
    
    # print(str(edited_substance))

    return render(request, 'subadd/edited.html', MiscMethods.add_header_info(context))


@login_required
def detail(request, substance_id):
    """
    View provides details on any particular substance record.  Hands things
    off to the detail template for rendering.

    :param request:
    :param substance_id:
    :return:
    """

    context = {}

    try:
        # substance = get_object_or_404(Substance, pk=substance_id)
        context['substance'] = Substance.objects.get(pk=substance_id)
    except Substance.DoesNotExist:
        # raise Http404("Substance does not exist :|")
        context['error_message'] = "The substance you are looking for does not seem to exist..."

    return render(request, 'subadd/detail.html', MiscMethods.add_header_info(context))


@login_required
def add_sub_class(request):
    """
    View provides the ability to add a new SubstanceClass.

    :param request:
    :return:
    """

    sub_classes = SubstanceClass.objects.all()

    if request.method != 'POST':
        add_sub_class_form = SubstanceClassForm()

        return render(request, 'subadd/add_class.html', MiscMethods.add_header_info({'substance_class': None,
                                                                                     'substance_classes': sub_classes,
                                                                                     'add_sub_class_form':
                                                                                     add_sub_class_form}))

    else:
        add_sub_class_rec = SubstanceClass(name=request.POST['name'], desc=request.POST['desc'])

        try:
            add_sub_class_rec.save()

            context = {'user_message': "Substance classification added successfully!",
                       'substance_classes': sub_classes,}

        except Exception as e:
            error_message = "Unable to save to db: " + str(e) + " admin: " + str(add_sub_class_rec)

            add_sub_class_form = SubstanceClassForm({'name': request.POST['name'], 'desc': request.POST['desc'],})

            context = {'add_sub_class_form': add_sub_class_form, 'error_message': error_message,
                       'substance_classes': sub_classes,}

        return render(request, 'subadd/add_class.html', MiscMethods.add_header_info(context))


@login_required
def sub_class_details(request, class_id):
    """
    View shows the details for a given classification of substances, including
    the substances classified under it currently.

    :param request:
    :param class_id:
    :return:
    """

    class_details = SubstanceClass.objects.get(id=class_id)
    substances_in_class = Substance.objects.filter(sub_class=class_details.id)

    paginator = Paginator(substances_in_class, 10)  # 15 admins per page

    page = request.GET.get('page')
    subs = paginator.get_page(page)

    return render(request, 'subadd/class_details.html',
                  MiscMethods.add_pagination_info(MiscMethods.add_header_info({'class_details': class_details,
                                                                               'substances': subs,}), subs))

subadd/templates/subadd/add.html
{% extends 'home/lasttime_head.html' %}

{% block main_page_content %}
  <h2>Add Substance</h2>

  <form action="{% url 'subadd:addentry' %}" method="post">

    {% csrf_token %}

   <table>

     {{ add_sub_form.as_table }}

    </table>

    <br>

    {% if add_sub_form %}

      <input type="submit" value="Add Substance" />

    {% endif %}
      
  </form>
{% endblock main_page_content %}

subadd/templates/subadd/add_class.html
{% extends 'home/lasttime_head.html' %}

{% block main_page_content %}
  <h2>Existing Substance Classes</h2>

    {% if substance_classes %}
        <ul>
          {% for sub_class in substance_classes %}
            <li><a href="{% url 'subadd:sub_class_details' sub_class.id %}">{{ sub_class.name }}</a></li>
          {% endfor %}
        </ul>
    {% endif %}

  <h2>Add Substance Classification</h2>

    <form action="{% url 'subadd:add_sub_class' %}" method="post">

        {% csrf_token %}

        <table>

            {{ add_sub_class_form.as_table }}

        </table>

        <br>

        <input type="submit" value="Add Substance Classification" />

    </form>
{% endblock main_page_content %}

subadd/templates/subadd/class_details.html
{% extends 'home/lasttime_head.html' %}

{% block main_page_content %}
  <h2>{{ class_details.name }} Details</h2>

  <p>Description:</p>
  <p>{{ class_details.desc }}</p>

  <h2>Substances in Class</h2>

  {% if substances %}
    <ul>
      {% for sub in substances %}
        <li><a href="{% url 'subadd:detail' sub.id %}">{{ sub }}</a></li>
      {% endfor %}
    </ul>
  {% endif %}
{% endblock main_page_content %}

subadd/templates/subadd/detail.html
{% extends 'home/lasttime_head.html' %}

{% block main_page_content %}
 {% if substance %}
  <h2>
    {{ substance.sci_name }} ({{ substance.common_name }})
  </h2>

  <table>
    <tr>
      <td>[Active] Half-life:</td>
      <td>{{ substance.active_half_life }}</td>
    </tr>
    <tr>
      <td>Metabolic Half-life:</td>
      <td>{{ substance.half_life }}</td>
    </tr>
    <tr>
      <td>Lipid (fat) soluble?</td>
      <td>
        {% if substance.lipid_solubility %}
          Yes
        {% else %}
          No
        {% endif %}
      </td>
    </tr>
      <tr>
          <td>Dosage Units:</td>
          <td>{{ substance.units }}</td>
      </tr>
  </table>
 {% endif %}
{% endblock main_page_content %}

subadd/templates/subadd/edit_sub.html
{% extends 'home/lasttime_head.html' %}

{% block main_page_content %}
  <h2>Edit Substance</h2>

  {% if substance_form %}

    <form action="{% url 'subadd:edited_sub' sub_id %}" method="post">

      {% csrf_token %}

      <table>

        {{ substance_form.as_table }}

      </table>

      <br><p>
      <input type="submit" value="Submit Changes" />

    </form>

  {% else %}

    <form action="{% url 'subadd:edit_sub' %}" method="post">

    {% csrf_token %}

    <ul>

      {% for sub in substances %}
        <li><input type="radio" name="sub_to_edit" value="{{ sub.id }}">{{ sub.common_name }}</input></li>
      {% endfor %}

    </ul>

    <br><p>
    <input type="submit" value="Select Substance to Edit" />

    </form>

  {% endif %}
{% endblock main_page_content %}

subadd/templates/subadd/edited.html
{% extends 'home/lasttime_head.html' %}

{% block main_page_content %}
  <h2>Edited Substance</h2>

  <p>
      Common name: {{ edited_substance.common_name }}<br>
      Scientific name: {{ edited_substance.sci_name }}<br>
      Detectable half-life: {{ edited_substance.half_life }}<br>
      Active half-life: {{ edited_substance.active_half_life }}<br>
      Lipid soluble: {% if edited_substance.lipid_solubility %} True {% else %} False {% endif %}<br>

{% endblock main_page_content %}

subadd/templates/subadd/index.html
{% extends 'home/lasttime_head.html' %}

{% block main_page_content %}
<h2>Substance List</h2>

{% if all_subs %}

  <ul>

    {% for sub in all_subs %}

      <li>
        <a href="{% url 'subadd:detail' sub.id %}">{{ sub.common_name }}
        </a>
      </li>

    {% endfor %}

  </ul>

 {% else %}

  <h3>There are no database entries</h3>

{% endif %}
{% endblock main_page_content %}

{% block default_trailer %}
  {% if user.is_authenticated %}
   <div class="botnav">
     <a href="{% url 'subadd:add' %}">Add new substance</a>
     <a href="{% url 'subadd:add_sub_class' %}">Substance classes</a>
     <a href="{% url 'subadd:edit_sub' %}">Edit Substance</a>
     <a href="/accounts/logout">Log out</a>
   </div>
  {% else %}
   <div class="botnav">&nbsp;</p></div>
  {% endif %}
{% endblock default_trailer %}