dox/urls.py
from django.urls import path

from . import views

app_name = 'dox'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:topic_id>/', views.detail, name='detail'),
    path('app_dox', views.per_app_docs, name='per_app_dox'),
    path('app_dox_detail/<int:topic_id>/', views.sv_detail, name='app_dox_detail'),
]

home/urls.py
from django.urls import path

from . import views

app_name = "home"
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('create_user/', views.create_user_interface, name='create_user_interface'),
    path('user_created/', views.create_user_interface, name='user_created'),
]

lasttime/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('subadd/', include('subadd.urls')),
    path('recadm/', include('recadm.urls')),
    path('dataview/', include('dataview.urls')),
    # path('home/', include('home.urls')),
    path('', include('home.urls')),
    path('dox/', include('dox.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
]

home/models.py
from django.db import models


class NavInfo(models.Model):
    """
    Holds the navbar information.
    """

    link = models.CharField(max_length=20)
    link_text = models.CharField(max_length=30)

    def __str__(self):
        return self.link + " with text: " + self.link_text


class HeaderInfo(models.Model):
    """
    Holds the header text.
    """

    motto = models.CharField(max_length=40)
    mission = models.CharField(max_length=180)

    def __str__(self):
        return self.motto + ": " + self.mission

home/forms.py
from django import forms

from lasttime.myglobals import Const


class NewUserForm(forms.Form):
    username = forms.CharField(label='User name', max_length=10)
    email = forms.EmailField(label='Email address', required=False,
                             help_text='Only required for password reset capability')
    first_name = forms.CharField(label='First name', max_length=15)
    last_name = forms.CharField(label='Last name', max_length=25)
    tz = forms.CharField(label='Local time zone', max_length=20, initial=Const.Time_Zone)
    password = forms.CharField(label='Password', max_length=20)

home/views.py
from django.shortcuts import render
from django.views import generic
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required

from .models import NavInfo, HeaderInfo
from .forms import NewUserForm
from lasttime.myglobals import Const, MiscMethods


class IndexView(generic.ListView):
    """
    Just a simple page giving links for logging in or creating a new user.
    """

    model = HeaderInfo
    template_name = 'home/index.html'

    def get_context_data(self, **kwargs):
        page_data = {}

        return MiscMethods.add_header_info(page_data)


def create_user_interface(request):
    """
    Method is utilized for the user creation page.

    :param request:
    :return:
    """

    if request.method == "POST":
        context = {}

        try:
            user = User.objects.create_user(request.POST['username'], request.POST['email'], request.POST['password'])
            user.first_name = request.POST['first_name']
            user.last_name = request.POST['last_name']
            user.tz = Const.Time_Zone   # obviously this will need to be changed when we add user TZ selection
            user.save()     # this will need to be in an error handling block at some point here
        except Exception as ex:
            create_user_form = NewUserForm
            return render(request, 'home/create_user.html', MiscMethods.add_header_info({'create_user_form':
                                                                                             create_user_form,
                                                                                         'error_message':
                                                                                             "Error saving: " +
                                                                                             str(ex),}))

        context['username'] = user.username

        return render(request, 'home/user_created.html', MiscMethods.add_header_info(context))
    else:
        create_user_form = NewUserForm()

        return render(request, 'home/create_user.html', MiscMethods.add_header_info({'create_user_form':
                                                                                     create_user_form}))

home/templates/home/create_user.html
{% extends 'home/lasttime_head.html' %}
{% block main_page_content %}
  <h1>Create New User</h1>

  {% if not user.is_authenticated %}

  <form action="{% url 'home:user_created' %}" method="post">

    {% csrf_token %}

    <table>

      {{ create_user_form.as_table }}

    </table>

    <p>
    <input type="submit" value="Submit User Data" />

  </form>

  {% else %}

  <h2>You're already logged in, silly.</h2>

  {% endif %}
{% endblock main_page_content %}

home/templates/home/index.html
{% extends 'home/lasttime_head.html' %}

{% block main_page_content %}
  {% if not user.is_authenticated %}

    <p><a href="{% url 'login' %}">Log in</a></p>
    <p><a href="{% url 'home:create_user_interface' %}">Create new user</a></p>

  {% endif %}
{% endblock main_page_content %}

home/templates/home/lasttime_head.html
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN">
<html lang="en">
{% load static %}
{% block header_thru_navbar %}
 <head>
     <title>LastTime</title>
     <!-- <META HTTP-EQUIV="CONTENT-SCRIPT-TYPE" CONTENT="～"> -->
     <LINK REV="MADE" HREF="mailto:damo.gets@gmail.com">
     <LINK REL="NEXT" HREF="http://d-resources.hopto.org/">
     <!-- <META HTTP-EQUIV="CONTENT-TYPE" CONTENT="～"> -->
     <link rel="stylesheet" type="text/css"
           href="{% static 'home/lasttime.css' %}">
 </head>
 <body>

  <div class="header">
      <h1 class="slogan">{{ header_info.motto }}</h1>
      <h3 class="mission">{{ header_info.mission }}</h3>
  </div>

   <div class="topnav">
      {% if user.is_authenticated %}
      {% for nav_item in links %}
       <a href="{% url nav_item.link %}">
           {{ nav_item.link_text }}
       </a>
      {% endfor %}
      {% else %}
       <p>&nbsp;
      {% endif %}
  </div>

  {% if error_message or user_message %}
  <div class="err"><center>
      {{ error_message }}&nbsp; {{ user_message }}
  </center></div>
  {% endif %}
{% endblock header_thru_navbar %}

   <!--
  {# NOTE: Here is where we'll want probably some sort of logo image and some
       text describing things a little more thoroughly than the slogan and
       mission statement #}
    -->

  {% block main_page_content %}{% endblock main_page_content %}

{% block page_navigation %}
  {% if page_number %}
  <p>&nbsp;
  <div class="pagination">
    <span class="step-links">
        {% if has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_number }} of {{ num_pages }}.
        </span>

        {% if has_next %}
            <a href="?page={{ next_page_number }}">next</a>
            <a href="?page={{ num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
  </div>
  {% endif %}
{% endblock page_navigation %}

{% block default_trailer %}

  {% if user.is_authenticated %}
   <div class="botnav"><a href="/accounts/logout">Log out</a></div>
  {% else %}
   <div class="botnav">&nbsp;</p></div>
  {% endif %}

 </body>
</html>
{% endblock default_trailer %}

home/templates/home/user_created.html
{% extends 'home/lasttime_head.html' %}

{% block main_page_content %}
  <h2>User {{ username }} created!</h2>

  <p>Please go ahead and <a href="{% url 'home:index' %}"><i>log in</i></a>.</p>
{% endblock main_page_content %}