dox/urls.py
from django.urls import path

from . import views

app_name = 'dox'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:topic_id>/', views.detail, name='detail'),
    path('app_dox', views.per_app_docs, name='per_app_dox'),
    path('app_dox_detail/<int:topic_id>/', views.sv_detail, name='app_dox_detail'),
]

lasttime/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('subadd/', include('subadd.urls')),
    path('recadm/', include('recadm.urls')),
    path('dataview/', include('dataview.urls')),
    # path('home/', include('home.urls')),
    path('', include('home.urls')),
    path('dox/', include('dox.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
]

recadm/urls.py
from django.urls import path

from . import views

app_name = 'recadm'
urlpatterns = [
    path('<int:topic_id>/', views.detail, name='detail'),
    path('', views.index, name='index'),
    path('add', views.add, name='add'),
    path('save_admin', views.save_admin, name='save_admin'),
    path('edit/<int:admin_id>/', views.edit, name='edit'),
    path('add_usual_suspect', views.add_usual_suspect, name='add_usual_suspect'),
    path('save_usual_suspect_admin', views.save_usual_suspect_admin, name='save_usual_suspect_admin'),
    path('delete_admin', views.delete_admin, name='delete_admin'),
    path('prune_database_by_date', views.prune_database_by_date, name='prune_database_by_date'),
]

recadm/models.py
from django.db import models
from django.utils import timezone

# Create your models here.


# class Usage(models.Model):
#     sub = models.ForeignKey('subadd.Substance', on_delete=models.CASCADE)
#     dosage = models.IntegerField()
#     timestamp = models.DateTimeField('time administered', default=timezone.now)
#     notes = models.CharField(max_length=160)

recadm/forms.py
from django import forms
from django.db import models
from django.utils import timezone
from django.forms import ModelForm, Textarea
from django.contrib.auth.models import User

from subadd.forms import Substance


class Usage(models.Model):
    """
    Model holds the information relevant to each particular substance's
    administration.
    """

    sub = models.ForeignKey('subadd.Substance', on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=6)
    dosage = models.DecimalField(max_digits=7, decimal_places=3)
    timestamp = models.DateTimeField('time administered', default=timezone.now)
    notes = models.CharField(max_length=512, blank=True)

    def __str__(self):
        return str(self.sub) + " (" + str(self.dosage) + ") administered to: " + self.user.username + \
               " at " + str(self.timestamp)


class UsageForm(ModelForm):
    """
    Form is (clearly) derived from the Usage class, above; holds the fields
    necessary to be filled out by hand for the administration record.

    TODO: Find out how to append or prepend the dosage units to the dosage form
    """

    class Meta:
        model = Usage
        fields = ['sub', 'dosage', 'timestamp', 'notes']
        labels = {
            'sub': 'Substance',
            'dosage': 'Dosage in [what?]'
        }
        widgets = {
            'notes': Textarea(attrs={'cols': 60, 'rows': 9})
        }


class UsualSuspect(models.Model):
    """
    Models holds the information relevant to a UsualSuspect, ie a predefined
    substance's usage information (including particular dosage, notes, etc, for
    one-click additions of a usage).
    """

    name = models.CharField(max_length=32, unique=True)
    sub_id = models.ForeignKey('subadd.Substance', on_delete=models.CASCADE)
    dosage = models.DecimalField(max_digits=7, decimal_places=3)
    notes = models.CharField(max_length=512, blank=True)

    def __str__(self):
        return self.name + ": " + self.notes  # we'll add more to this later


class UsualSuspectForm(ModelForm):
    """
    Form for adding or changing a UsualSuspect.
    """

    class Meta:
        model = UsualSuspect
        fields = ['name', 'sub_id', 'dosage', 'notes']
        labels = {
            'name': 'Name',
            'sub_id': 'Substance',
            'dosage': 'Dosage amount',
            'notes': 'Notes',
        }
        widgets = {
            'notes': Textarea(attrs={'cols': 60, 'rows': 9})
        }

recadm/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from django.core.paginator import Paginator
from datetime import datetime
from pytz import timezone

from lasttime.myglobals import MiscMethods, Const

from subadd.forms import Substance
from .forms import Usage, UsageForm, UsualSuspect, UsualSuspectForm


@login_required
def index(request):
    """
    View shows the details of administrations; it will, at some point,
    obviously have to be chopped down for a reasonable subset of the
    list, but it's good for testing purposes.  Passes the view off via
    the recadm/index template.

    :param request:
    :return:
    """

    recent_administrations = Usage.objects.filter(user=request.user).order_by('sub', '-timestamp')
    paginator = Paginator(recent_administrations, 15)   # 15 admins per page

    page = request.GET.get('page')
    administrations = paginator.get_page(page)

    mydata = []
    for administration in administrations:  # recent_administrations:
        # localize timestamp?
        if MiscMethods.is_localization_needed(administration.timestamp):
            local_dt = MiscMethods.localize_timestamp(administration.timestamp)
        else:
            local_dt = administration.timestamp

        mydata.append({'ts': local_dt,
                       'id': administration.id,
                       'dosage': administration.dosage,
                       'units': administration.sub.units,
                       'substance_name': administration.sub,})

    context = {'mydata': mydata, 'user': request.user, 'administrations': administrations,}

    return render(request, 'recadm/index.html',
                  MiscMethods.add_pagination_info(MiscMethods.add_header_info(context), administrations))


@login_required
def add(request):
    """
    View for adding a particular administration record.  Passes the view off
    to the add_entry template.

    :param request:
    :return:
    """

    substances = Substance.objects.all()
    usual_suspects = UsualSuspect.objects.all()

    mydata = []

    add_administration_form = UsageForm()

    for sub in substances:
        mydata.append({'name': sub.common_name, 'id': sub.id,})

    context = {
        'mydata': mydata,
        'timestamp': "YYYY-mm-dd HH:MM:SS",
        # 'timestamp': datetime.now(),  # the other option
        'usual_suspects': usual_suspects,
        'add_admin_form': add_administration_form,
    }

    return render(request, 'recadm/add_entry.html', MiscMethods.add_header_info(context))


@login_required
def save_admin(request):
    """
    View is called when add_entry is submitted and passes the data off here in
    order to save it to the database.  It returns the viewer back to the index
    template, in order to see the results of the database addition at the top
    of the administration records.

    :param request:
    :return:
    """

    if request.method == "POST":
        add_administration_form = UsageForm({'sub': request.POST['sub'],
                                             'dosage': request.POST['dosage'],
                                             'timestamp': request.POST['timestamp'],
                                             'notes': request.POST['notes']})
        # localize the timestamp
        central_tz = timezone(Const.Time_Zone)
        timestamp = central_tz.localize(datetime.strptime(request.POST['timestamp'], '%Y-%m-%d %H:%M:%S'))
        print(str(timestamp))
        new_administration = Usage(sub=Substance.objects.get(id=request.POST['sub']), user=request.user,
                                   dosage=request.POST['dosage'], timestamp=timestamp,
                                   notes=request.POST['notes'])

        try:
            new_administration.save()
        except Exception as e:
            error_message = "Unable to save to db: " + str(e) + "admin: " + str(new_administration)

            context = {'add_admin_form': add_administration_form,
                       'error_message': error_message,}

            return render(request, 'recadm/add_entry.html', MiscMethods.add_header_info(context))

    # code for the successful save of the record and return to the index
    # follows here
    mydata = []

    recent_administrations = Usage.objects.filter(user=request.user).order_by('-timestamp')
    paginator = Paginator(recent_administrations, 15)  # 15 admins per page

    page = request.GET.get('page')
    administrations = paginator.get_page(page)

    for administration in administrations:
        # localization needed?
        if MiscMethods.is_localization_needed(administration.timestamp):
            tmp_dt = MiscMethods.localize_timestamp(administration.timestamp)
        else:
            tmp_dt = administration.timestamp

        mydata.append({'ts': tmp_dt,
                       'id': administration.id,
                       'dosage': administration.dosage,
                       'substance_name': administration.sub,})

    context = {'mydata': mydata, 'administrations': administrations,}

    return render(request, 'recadm/index.html', MiscMethods.add_header_info(context))


@login_required
def detail(request, topic_id):
    """
    Provides the details on any particular administration's notes, primarily
    (or maybe solely) linked via the index page's summary of different
    administration details.

    :param request:
    :param topic_id:
    :return:
    """

    try:
        admin_details = Usage.objects.get(id=topic_id, user=request.user)
    except Usage.DoesNotExist:
        return render(request, 'recadm/details.html',
                      MiscMethods.add_header_info({'error_message':
                                                   "The Usage records you requested do not seem to exist...",}))

    # localization needed?
    if MiscMethods.is_localization_needed(admin_details.timestamp):
        tmp_dt = MiscMethods.localize_timestamp(admin_details.timestamp)
    else:
        tmp_dt = admin_details.timestamp

    context = {
        'sub': admin_details.sub,
        'dosage': admin_details.dosage,
        'units': admin_details.sub.units,
        'timestamp': tmp_dt,
        'notes': admin_details.notes,
        'admin_id': admin_details.id,
    }

    return render(request, 'recadm/details.html', MiscMethods.add_header_info(context))


@login_required
def edit(request, admin_id):
    """
    Provides the capability to edit an existing administration.

    :param request:
    :param admin_id:
    :return:
    """

    context = {
        'id': admin_id,
    }

    if request.method != "POST":
        # give 'em the form
        try:
            admin_details = Usage.objects.get(id=admin_id, user=request.user)
            context['admin_form'] = UsageForm(instance=admin_details)
            
        except Exception as ex:
            context['error_message'] = "Invalid administration record request: " + str(ex)
            # here we should really be throwing things back to the detail view,
            # but with an error message explaining what happened; waiting until
            # global error message handling is completed before doing this,
            # however

            return render(request, 'recadm/edit_admin.html', MiscMethods.add_header_info(context))

        return render(request, 'recadm/edit_admin.html', MiscMethods.add_header_info(context))

    new_admin_deets = Usage.objects.get(id=admin_id, user=request.user)
    new_admin_deets.sub = Substance.objects.get(id=request.POST['sub'])
    new_admin_deets.dosage = request.POST['dosage']
    new_admin_deets.timestamp = MiscMethods.str_to_datetime(request.POST['timestamp'])
    new_admin_deets.notes = request.POST['notes']

    # localize?
    if MiscMethods.is_localization_needed(new_admin_deets.timestamp):
        new_admin_deets.timestamp = MiscMethods.localize_timestamp(new_admin_deets.timestamp)

    try:
        new_admin_deets.save()
    except Exception as ex:
        context['error_message'] = "Unable to save new administration details: " + str(ex)
        context['admin_form'] = UsageForm(instance=new_admin_deets)

        return render(request, 'recadm/edit_admin.html', MiscMethods.add_header_info(context))

    # again, this is another one waiting for the global user/error message
    # displaying code, but in another area
    context['user_message'] = "Saved new administration details."
    context['admin_form'] = UsageForm(instance=new_admin_deets)

    # return render(request, 'recadm/edit_admin.html', MiscMethods.add_header_info(context))
    # so below here...  this really isn't the way to be doing this, with an absolute URL/path, but the other ways
    # weren't working, and this one was, so I took the easy out...  :P
    return redirect('/recadm/', context=MiscMethods.add_header_info(context))


@login_required
def add_usual_suspect(request):
    """
    Provides capability for adding a usual suspect to the database.

    :param request:
    :return:
    """

    if request.method != 'POST':
        # display the form and get what we need for a new US entry
        # add_usual_suspect_form = UsualSuspectForm()

        return render(request, 'recadm/add_usual_suspect.html', MiscMethods.add_header_info({'add_usual_suspect_form':
                                                                                             UsualSuspectForm(),}))

    else:
        context = {}
        # validate (if necessary) and save the form contents
        new_us = UsualSuspect()

        new_us.name = request.POST['name']
        new_us.sub_id = Substance.objects.get(id=request.POST['sub_id'])
        new_us.dosage = request.POST['dosage']
        new_us.notes = request.POST['notes']

        try:
            new_us.save()
        except Exception as ex:
            context['error_message'] = "Unable to save new usual suspect: " + str(ex)

recadm/templates/recadm/add_entry.html
{% extends 'home/lasttime_head.html' %}
{% block main_page_content %}
<h2>Record Medication Administration</h2>

<table>
    <tr>
      <td>
        <!-- standard 'raw data' administration addition lies here -->
        <form action="{% url 'recadm:save_admin' %}" method="post">
          {% csrf_token %}

          <table>
              {{ add_admin_form.as_table }}
          </table>

          <br>
          <input type="submit" value="Record Med Administration" />
        </form>
      </td>
      <td>
          <!-- here is where the usual suspect administration addition lies -->
          {% if usual_suspects %}

            <form action="{% url 'recadm:save_usual_suspect_admin' %}" method="post">
                {% csrf_token %}
                <p>Usual Suspect:</p>
                {% for usual_suspect in usual_suspects %}
                    <input type="radio" name="us_value" value="{{ usual_suspect.id }}">
                        {{ usual_suspect.name }}
                    </input>
                    <br>
                {% endfor %}
                  <p>Timestamp:</p>
                  <input type="text" name="timestamp" placeholder="{{ timestamp }}" maxlength="20" />
                  <br>
                <br><br>
                <input type="submit" value="Record Usual Suspect Administration" />
            </form>

          {% else %}
            <h3>No Usual Suspects Exist for Addition!</h3>
          {% endif %}
      </td>
    </tr>
</table>
{% endblock main_page_content %}

{% block default_trailer %}
  <div class="botnav">
      <a href="{% url 'recadm:index' %}">Administration Index</a>
  </div>

 </body>
</html>
{% endblock default_trailer %}

recadm/templates/recadm/add_usual_suspect.html
{% extends 'home/lasttime_head.html' %}

{% block main_page_content %}
  <h2>Add Usual Suspect</h2>

    <form action="{% url 'recadm:add_usual_suspect' %}" method="post">

        {% csrf_token %}

        <table>
            {{ add_usual_suspect_form.as_table }}
        </table>

        <br>

        <input type="submit" value="Save Usual Suspect" />
    </form>
{% endblock main_page_content %}

recadm/templates/recadm/delete_admin.html
{% extends 'home/lasttime_head.html' %}

{% block main_page_content %}
  <h2>Delete Administration(s)</h2>

  {% if admins %}
    <form action="{% url 'recadm:delete_admin' %}" method="post">

        {% csrf_token %}

        <table>
            <!--
                NOTE: We will need to add a 'select all' checkbox here, with
                      applicable javascript, as soon as motivation is available
                      for such
              -->

            <tr>
                <th>Administration Information</th>
                <th>Delete?</th>
            </tr>
            {% for admin in admins %}
                <tr>
                    <td>{{ admin }}</td>
                    <td><center>
                        <input type="checkbox" name="admin_checks" value="{{ admin.id }}" />
                    </center></td>
                </tr>
            {% endfor %}
        </table>

        <br>
        <input type="submit" value="Delete Administrations" />

    </form>
  {% elif selected_admins %}
    <!-- confirm that the administrations are to be deleted -->

    <h2>You are about to delete the following administrations!</h2>
    <p><b>NOTE</b>:  This cannot be undone!</p>

    <ul>
        {% for admin in selected_admins %}
            <li>{{ admin }}</li>
        {% endfor %}
    </ul>

    <form action="{% url 'recadm:delete_admin' %}" method="post">

        {% csrf_token %}

        <br>
        <p>Clicking this box will delete these administrations (<i>forever</i>)!</p>
        {% for id in selected_admin_ids %}
            <input type="hidden" name="selected_admin_ids" value="{{ id }}" />
        {% endfor %}
        <input type="hidden" name="delete_confirmed" value="delete_confirmed" id="delete_confirmed" />
        <input type="submit" value="Permanently Delete Administrations!" />

    </form>

  {% else %}
    <h3>No Administrations Available!</h3>
  {% endif %}

{% endblock main_page_content %}
{% block default_trailer %}
{% endblock default_trailer %}

recadm/templates/recadm/details.html
{% extends 'home/lasttime_head.html' %}
{% block main_page_content %}
  <h3>Administration Details</h3>

  <table>
      <tr>
          <td>
              Date:
          </td>
          <td>
              {{ timestamp }}
          </td>
      </tr>
      <tr>
          <td>
              Substance:
          </td>
          <td>
              {{ sub }}
          </td>
      </tr>
      <tr>
          <td>
              Dosage:
          </td>
          <td>
              {{ dosage }}{{ units }}
          </td>
      </tr>
      <tr>
          <td>
              Notes:
          </td>
          <td>
              {{ notes }}
          </td>
      </tr>
  </table>
{% endblock main_page_content %}

{% block default_trailer %}
  <div class="botnav">
      <a href="{% url 'recadm:index' %}">Administration Index</a>
      <a href="{% url 'recadm:add' %}">Add Administration</a>
      <a href="{% url 'recadm:edit' admin_id %}">Edit This Administration</a>
  </div>

 </body>
</html>
{% endblock default_trailer %}

recadm/templates/recadm/edit_admin.html
{% extends 'home/lasttime_head.html' %}

{% if user_message or error_message %}
 <div class="err">
     {{user_message}}&nbsp;{{error_message}}
 </div>
{% endif %}

{% block main_page_content %}
  <form action="{% url 'recadm:edit' id %}" method="post">
    {% csrf_token %}

    <table>
        {{ admin_form.as_table }}
    </table>

    <input type="submit" value="Save New Admin Details" />
  </form>
{% endblock main_page_content %}

{% block default_trailer %}
  <div class="botnav">
      <a href="{% url 'recadm:index' %}">Administration Index</a>
  </div>

 </body>
</html>
{% endblock default_trailer %}

recadm/templates/recadm/index.html
{% extends 'home/lasttime_head.html' %}

{% block main_page_content %}
  {% if mydata %}
  <ul>
    {% for admin_details in mydata %}
      <li><a href="{% url 'recadm:detail' admin_details.id %}">
        {{ admin_details.ts }}: {{ admin_details.dosage }}{{ admin_details.units }}
        {{ admin_details.substance_name }}
      </a></li>
    {% endfor %}
  </ul>

{% else %}

  <p>No administrations have been recorded at this point.</p>

{% endif %}
{% endblock main_page_content %}

{% block default_trailer %}
  <div class="botnav">
      <a href="{% url 'recadm:add' %}">Add Administration</a>
      <a href="{% url 'recadm:delete_admin' %}">Delete Administration(s)</a>
      <a href="{% url 'recadm:add_usual_suspect' %}">Add Usual Suspect</a>
      <a href="{% url 'recadm:prune_database_by_date' %}">Prune Database</a>
      <a href="/accounts/logout">Log out</a>
  </div>

 </body>
</html>
{% endblock default_trailer %}

recadm/templates/recadm/prune_database_by_date.html
{% extends 'home/lasttime_head.html' %}

{% block main_page_content %}
  {% if not need_verification and not verified %}
    <h2>Prune Database</h2>

    <p>Here you can remove or archive your older administration entries from the database.</p>

    <br>

    <form action="{% url 'recadm:prune_database_by_date' %}" method="post">
        {% csrf_token %}

        <table>
            <tr>
                <td>Substance:</td>
                <td>
                  {% for sub in all_subs %}
                    <input type="radio" name="sub_to_prune" value="{{ sub.id }}">{{ sub.common_name }}</input><br>
                  {% endfor %}
                </td>
            </tr>
            <tr>
                <td>Date to remove admins prior to:</td>
                <td><input type="text" name="prune_prior_to_date" placeholder="YYYY-mm-dd HH:MM:SS" maxlength="20" /></td>
            </tr>
        </table>

        <input type="hidden" name="need_verification" value="True" />
        <p><input type="submit" name="Wipe Administrations" />
    </form>

  {% elif need_verification %}

    {% if administrations %}
      <ol>
        {% for admin in administrations %}
          <li>{{ admin }}</li>
        {% endfor %}
      </ol>
    {% endif %}

    <br>
    <form action="{% url 'recadm:prune_database_by_date' %}" method="post">
      {% csrf_token %}
      <br>Verify that you want to purge the database irreversibly of these entries by checking here:
        <input type="checkbox" name="verified" /><br>
        <input type="hidden" name="prune_prior_to_date" value="{{ prune_prior_to_date }}" />
        <input type="hidden" name="sub_to_prune" value="{{ sub_to_prune }}" />
      <p><input type="submit" name="Purge database irreversibly!" />
    </form>

  {% endif %}

{% endblock main_page_content %}
{% block default_trailer %}
  <div class="botnav">
      <a href="{% url 'recadm:add' %}">Add Administration</a>
      <a href="{% url 'recadm:delete_admin' %}">Delete Administration(s)</a>
      <a href="{% url 'recadm:add_usual_suspect' %}">Add Usual Suspect</a>
      <a href="{% url 'recadm:prune_database_by_date' %}">Prune Database</a>
      <a href="/accounts/logout">Log out</a>
  </div>

 </body>
</html>
{% endblock default_trailer %}

recadm/templates/recadm/usual_suspect_admin_added.html
{% extends 'home/lasttime_head.html' %}
{% block main_page_content %}
  {% if error_message %}
    <h2>Unable to Save Administration</h2>

    <p>We're sorry, something is borked in the administration addition via
    <b>usual suspect</b> feature.  We're going to get on top of this as soon as
    possible here!</p>
  {% else %}
    <h2>Usual Suspect Administration Saved</h2>

  {% endif %}
{% endblock main_page_content %}