dataview/urls.py
from django.urls import path

from . import views

app_name = 'dataview'
urlpatterns = [
    # path('', views.IndexView.as_view(), name='index'),
    path('', views.index, name='index'),
    path('<int:pk>/', views.SubAdminDataView.as_view(), name='data_summary'),
    path('constrained_summary/<int:sub_id>/', views.day_constrained_summary, name='constrained_summary'),
    path('halflife/<int:sub_id>/', views.extrapolate_halflife_data, name='halflife'),
    path('dump_dose_graph_data/<int:sub_id>/', views.dump_dose_graph_data, name='dump_dose_graph_data'),
    path('dump_interval_graph_data/<int:sub_id>/', views.dump_interval_graph_data, name='dump_interval_graph_data'),
    path('dump_constrained_dose_graph_data/<int:sub_id>/', views.dump_constrained_dose_graph_data,
         name='dump_constrained_dose_graph_data'),
    path('class_data_summary/<int:class_id>/', views.class_data_summary, name='class_data_summary'),
    path('sclasses/', views.sclasses, name='sclasses'),
]

dox/urls.py
from django.urls import path

from . import views

app_name = 'dox'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:topic_id>/', views.detail, name='detail'),
    path('app_dox', views.per_app_docs, name='per_app_dox'),
    path('app_dox_detail/<int:topic_id>/', views.sv_detail, name='app_dox_detail'),
]

lasttime/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('subadd/', include('subadd.urls')),
    path('recadm/', include('recadm.urls')),
    path('dataview/', include('dataview.urls')),
    # path('home/', include('home.urls')),
    path('', include('home.urls')),
    path('dox/', include('dox.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
]

dataview/models.py
from django.db import models

# Create your models here.

dataview/views.py
from django.shortcuts import render, redirect
from django.views import generic
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import Paginator

from lasttime.myglobals import MiscMethods, Const

import datetime
from pytz import timezone
import json

from recadm.forms import Usage
from subadd.forms import Substance, SubstanceClass
from home.models import NavInfo, HeaderInfo
from . import dataview_support


@login_required
def index(request):
    all_subs = Substance.objects.all()
    filtered_subs = []
    context = {}

    for sub in all_subs:
        if Usage.objects.filter(sub=sub.pk, user=request.user).exists():
            print("Adding " + str(sub))
            filtered_subs.append(sub)

    print("Filtered subs: " + str(filtered_subs))

    paginator = Paginator(filtered_subs, 15)  # 15 admins per page

    page = request.GET.get('page')
    subs = paginator.get_page(page)

    print("subs: " + str(subs))

    context = {'relevant_subs': subs}

    return render(request, 'dataview/index.html', MiscMethods.add_pagination_info(MiscMethods.add_header_info(context),
                                                                                  subs))


class SubAdminDataView(LoginRequiredMixin, generic.DetailView):
    """
    Again, if I'm misunderstanding concepts about class/generic view
    implementation, this may have to be revised, but the idea behind this view/
    class is to provide a view of the data (averages, then eventually plasma
    drop-off graphing, etc) regarding the history of administrations of the
    particular substance in question.  It breaks down a lot of the specifics
    in order to be fed to the D3.js graphing system that is utilized in the
    applicable template.
    """

    model = Usage   # should've said all generic views need to know
    template_name = 'dataview/data_summary.html'  # needed to avoid using the default

    def get_context_data(self, **kwargs):
        usages = Usage.objects.filter(sub=self.kwargs['pk'], user=self.request.user).order_by("timestamp")
        # print("pk is: " + str(self.kwargs['pk']))

        # though it duplicates things, the following conditional just checks for errors that will screw up the graphing
        too_few_usages_error = False
        if len(usages) < 2:
            too_few_usages_error = True
        else:
            zero_interval_error = False
            prev_timestamp = None
            for use in usages:
                if prev_timestamp is not None and use.timestamp == prev_timestamp:
                    zero_interval_error = True

                prev_timestamp = use.timestamp

        if too_few_usages_error:
            return MiscMethods.add_header_info({'error_message': "Not enough usages to calculate statistics properly"})

        elif zero_interval_error:
            return MiscMethods.add_header_info({'error_message':
                                                "Zero intervals between datasets causing calculation errors"})

        else:
            # now we get to actually gathering/calculating stats
            # calculate usage statistics
            usage_data = dataview_support.get_usage_stats(usages)

            # timespan & average calculation
            span_data = dataview_support.get_interval_stats(usages)

            # having issues with this with <2 (or maybe it's <3) usages recorded; not stopping to fix it the right way
            # just yet here; next time work is done with this try to get to the bottom of it
            scale_factor = 1    # get_graph_normalization_divisor(span_data['longest'].total_seconds(), 600)

            return MiscMethods.add_header_info({'usages': usages, 'usage_count': usage_data['count'],
                                                'usage_average': usage_data['average'],
                                                'usage_high': usage_data['highest'],
                                                'usage_low': usage_data['lowest'], 'usage_total': usage_data['total'],
                                                'sub_dosage_units': usages[0].sub.units,
                                                'sub_name':
                                                    Substance.objects.filter(pk=self.kwargs['pk'])[0].common_name,
                                                'sub_id': self.kwargs['pk'], 'longest_span': span_data['longest'],
                                                'shortest_span': span_data['shortest'],
                                                'timespans': span_data['timespans'],
                                                'scale_factor': scale_factor, 'average_span': span_data['average'],})


@login_required
def day_constrained_summary(request, sub_id):
    """
    This method will just handle displaying a per-day constrained view of the
    dosages administered to this user per-sub, for now.  More functionality
    including variable time constraints will be added in the future.

    :param request:
    :param sub_id:
    :return:
    """

    usages = Usage.objects.filter(sub=sub_id, user=request.user).order_by("timestamp")
    sub_data = Substance.objects.filter(id=sub_id)

    # not going to bother with testing if there are too few usages for now; if
    # there weren't enough this should've prevented the user from getting this
    # far in the first place

    one_day = datetime.timedelta(days=1)
    usage_data = {}
    admins_start = MiscMethods.localize_timestamp(datetime.datetime.max - one_day)
    admins_end = MiscMethods.localize_timestamp(datetime.datetime.min + one_day)

    for use in usages:
        if MiscMethods.is_localization_needed(use.timestamp):
            local_datetime = MiscMethods.localize_timestamp(use.timestamp)
        else:
            local_datetime = use.timestamp

        if not str(local_datetime.date()) in usage_data:
            usage_data[str(local_datetime.date())] = float(use.dosage)
            # print("Creating " + str(local_datetime) + " to " + str(local_datetime.date()) + " @ " + str(use.dosage))

            # get our tabulated duration information
            if local_datetime < admins_start:
                admins_start = local_datetime
            if local_datetime > admins_end:
                admins_end = local_datetime
        else:
            usage_data[str(local_datetime.date())] += float(use.dosage)
            # print("Adding " + str(local_datetime) + " to " + str(local_datetime.date()) + " @ " + str(use.dosage))

        # prev_date = local_datetime.date()

    total_span = admins_end - admins_start

    max_dosage = 0
    min_dosage = 100000     # since Decimal.max isn't working, this should be big enough here
    cntr = 0
    total_dosed = 0
    for constrained_usage in usage_data:
        # get our max/min dosage information
        if usage_data[constrained_usage] > max_dosage:
            max_dosage = usage_data[constrained_usage]
        if usage_data[constrained_usage] < min_dosage:
            min_dosage = usage_data[constrained_usage]

        # for calculating average/total information
        cntr += 1
        total_dosed += usage_data[constrained_usage]

    average_dosed = total_dosed / cntr

    print("usage_data: " + str(usage_data))

    return render(request, 'dataview/constrained_dosage_summary.html',
                  MiscMethods.add_header_info({'usage_data': str(usage_data), 'sub_id': sub_id,
                                               'highest_dose': max_dosage, 'lowest_dose': min_dosage,
                                               'avg_dose': average_dosed, 'admins_start': admins_start,
                                               'admins_end': admins_end, 'duration': total_span,
                                               'sub_name': sub_data[0].common_name,}))


@login_required
def extrapolate_halflife_data(request, sub_id):
    """
    This method has a little more beef to it than most.  First it determines
    whether or not the substance passed is lipid soluble or not.  If it is,
    then it tries to determine whether or not it's talking about THC.  If so,
    it utilizes an algorithm based on the Mayo Clinic labs' standards for the
    detectability of THC in urine to determine the detectable half-life
    duration.  If the substance is lipid soluble but not THC, we return an
    error message due to not having enough specific data to work with that
    just yet.  If it's only water/plasma soluble, we calculate solely the
    standard elimination projection (which is done for THC, as well), which is
    based on the 5.7 * half-life projection that I was quoted by one of my
    health care professionals.

    :param request:
    :param sub_id:
    :return:
    """

    # TODO: modularize the lipid_soluble weed block below
    substance = Substance.objects.get(id=sub_id)
    context = {}
    elimination_data = {'full': None, 'detectable': None, 'relevant_since': None,
                        'last_usage':
                            Usage.objects.filter(sub=sub_id, user=request.user).order_by('-timestamp').first(),
                        'uses': 0}

    if substance.lipid_solubility and ('marijuana' in substance.common_name or 'weed' in substance.common_name):
        #process the information for the tweeds
        elimination_data = get_weed_stats(Usage.objects.filter(sub=sub_id, user=request.user).order_by('-timestamp'),
                                          substance.active_half_life)

    elif substance.lipid_solubility:
        # we can't process this yet
        context['error_message'] = \
            "We are not able to process half-life extrapolation for non-THC lipid soluble metabolites yet, sorry!"
    else:
        # last_usage = Usage.objects.filter(sub=sub_id, user=request.user).order_by('-timestamp').first()

dataview/templates/dataview/class_data_summary.html
{% extends 'home/lasttime_head.html' %}

{% block main_page_content %}
  <h2>Substances in Classification</h2>

  {% if subs %}
    <ul>
        {% for use in usages %}
            <li><a href="#{{ use.0 }}">{{ use.0 }}</a></li>
        {% endfor %}
    </ul>
  {% else %}
    <h3>No Substances Available!</h3>
  {% endif %}

  <h2>Usages Per Substance in Classification</h2>

  {% if usages %}
        {% for use_group in usages %}
            <a name="{{ use_group.0 }}"><h4>{{ use_group.0 }}</h4></a>

            {% if use_group.7 is not False %}
            <table summary="{{ use_group.0 }} Data Summary">
             <tr><td>
            {% endif %}
              <table summary="Administration Stats">
                <tr>
                    <td>Total Usages:</td>
                    <td>{{ use_group.3 }}</td>
                    <td>Total Administered:</td>
                    <td>{{ use_group.2 }}</td>
                </tr>
                <tr>
                    <td>Average per Usage:</td>
                    <td>{{ use_group.4 }}</td>
                    <td></td>
                    <td></td>
                </tr>
                <tr>
                    <td>Highest Dosage:</td>
                    <td>{{ use_group.5 }}</td>
                    <td>Lowest Dosage:</td>
                    <td>{{ use_group.6 }}</td>
                </tr>
              </table>

            {% if use_group.7 is not False %}
             </td>
             <td>
                 <table summary="Interval Stats">
                     <tr>
                         <td>Total Duration:</td>
                         <td>{{ use_group.7.total }}</td>
                     </tr>
                     <tr>
                         <td>Average Duration:</td>
                         <td>{{ use_group.7.average }}</td>
                     </tr>
                     <tr>
                         <td>Longest Duration:</td>
                         <td>{{ use_group.7.longest }}</td>
                     </tr>
                     <tr>
                         <td>Shortest Duration:</td>
                         <td>{{ use_group.7.shortest }}</td>
                     </tr>
                 </table>
             </td></tr>
            </table>
            {% endif %}

            <ul>
              {% for use in use_group.1 %}
                <li>{{ use }}</li>
              {% endfor %}
            </ul>

            <div id="graph_dosage_{{ use_group.0.id }}"></div>
            <!-- dosage graph -->
     <div class="dose_chart"></div>
     <script src="http://d3js.org/d3.v3.min.js" type="text/javascript"></script>
     <script type="text/javascript">
        let json_src_{{ use_group.0.id }} = '{% url 'dataview:dump_dose_graph_data' use_group.0.id %}';

        var margin = {top: 20, right: 20, bottom: 70, left: 40},
        width = 600 - margin.left - margin.right,
        height = 300 - margin.top - margin.bottom;

        var x = d3.scale.ordinal().rangeRoundBands([0, width], .05);
        var y = d3.scale.linear().range([height, 0]);

        var xAxis = d3.svg.axis()
            .scale(x)
            .orient("bottom")
            .ticks(5);

        var yAxis = d3.svg.axis()
            .scale(y)
            .orient("left")
            .ticks(10);

        var svg_{{ use_group.0.id }} = d3.select("#graph_dosage_{{ use_group.0.id }}").append("svg")
            .attr("width", width + margin.left + margin.right)
            .attr("height", height + margin.top + margin.bottom)
          .append("g")
            .attr("transform",
                  "translate(" + margin.left + "," + margin.top + ")");

        d3.json(json_src_{{ use_group.0.id }}, function(error, data) {
          var ouah = []
          var ouah2 = []
          var ouah3 = []
          for (var cntr = 0; cntr < data.dosages.length; cntr++) {
            ouah[cntr] = {}
            ouah2[cntr] = (cntr + 1);
            ouah3[cntr] = data.dosages[cntr];
            ouah[cntr].date = ouah2[cntr]
            ouah[cntr].value = ouah3[cntr]
          }

          console.log(ouah);

          ouah.forEach(function(d) {
              d.date = d.date;
              d.value = +d.value;
          });

          x.domain(ouah.map(function(d) { return d.date; }));
          y.domain([0, d3.max(ouah3)]);

          svg_{{ use_group.0.id }}.append("g")
              .attr("class", "x axis")
              .attr("transform", "translate(0," + height + ")")
              .call(xAxis)
            .selectAll("text")
              .style("text-anchor", "end")
              .attr("dx", "-.8em")
              .attr("dy", "-.55em")
              .attr("transform", "rotate(-90)" );

          svg_{{ use_group.0.id }}.append("g")
              .attr("class", "y axis")
              .call(yAxis)
            .append("text")
              .attr("transform", "rotate(-90)")
              .attr("y", 6)
              .attr("dy", ".71em")
              .style("text-anchor", "end")
              .text("Dosage in {{ sub_dosage_units }}");

          svg_{{ use_group.0.id }}.selectAll("bar")
              .data(ouah)
            .enter().append("rect")
              .style("fill", "steelblue")
              .attr("x", function(d) { return x(d.date); })
              .attr("width", x.rangeBand())
              .attr("y", function(d) { return y(d.value); })
              .attr("height", function(d) { return height - y(d.value); });

        });

       </script>

       <div id="graph_dosage_{{ use_group.0.id }}_2">&nbsp;</div>

            <!-- between dosage interval graph -->
     <div class="interval_chart"></div>
     <script src="http://d3js.org/d3.v3.min.js" type="text/javascript"></script>
     <script type="text/javascript">
let json_src_{{ use_group.0.id }}_2 = '{% url 'dataview:dump_interval_graph_data' use_group.0.id %}';

var margin = {top: 20, right: 20, bottom: 70, left: 40},
    width = 600 - margin.left - margin.right,
    height = 300 - margin.top - margin.bottom;

var x2 = d3.scale.ordinal().rangeRoundBands([0, width], .05);
var y2 = d3.scale.linear().range([height, 0]);

var xAxis2 = d3.svg.axis()
    .scale(x2)
    .orient("bottom")
    .ticks(10);

var yAxis2 = d3.svg.axis()
    .scale(y2)
    .orient("left")
    .ticks(10);

var svg2_{{ use_group.0.id }} = d3.select("#graph_dosage_{{ use_group.0.id }}_2").append("svg")
    .attr("width", width + margin.left + margin.right)
    .attr("height", height + margin.top + margin.bottom)
  .append("g")
    .attr("transform",
          "translate(" + margin.left + "," + margin.top + ")");

d3.json(json_src_{{ use_group.0.id }}_2, function(error, data) {

    var ouah_interval = [];
    for (var cntr = 0; cntr < data.timespans.length; cntr++) {
        ouah_interval[cntr] = {}
        ouah_interval[cntr].num = cntr + 1;
        ouah_interval[cntr].value = data.timespans[cntr];
    };

    ouah_interval.forEach(function(d) {
        d.num = d.num;
        d.value = +d.value;
    });

    //debugging
    //console.log(ouah_interval);

  x2.domain(ouah_interval.map(function(d) { return d.num; }));
  y2.domain([0, d3.max(ouah_interval, function(d) { return d.value; })]);

  svg2_{{ use_group.0.id }}.append("g")
      .attr("class", "x axis")
      .attr("transform", "translate(0," + height + ")")
      .call(xAxis2)
    .selectAll("text")
      .style("text-anchor", "end")
      .attr("dx", "-.8em")
      .attr("dy", "-.55em")
      .attr("transform", "rotate(-90)" );

  svg2_{{ use_group.0.id }}.append("g")
      .attr("class", "y axis")
      .call(yAxis2)
    .append("text")
      .attr("transform", "rotate(-90)")
      .attr("y2", 6)
      .attr("dy", ".71em")
      .style("text-anchor", "end")
      .text("Timespan in Hours");

  svg2_{{ use_group.0.id }}.selectAll("bar")
      .data(ouah_interval)
    .enter().append("rect")
      .style("fill", "steelblue")
      .attr("x", function(d) { return x2(d.num); })
      .attr("width", x2.rangeBand())
      .attr("y", function(d) { return y2(d.value); })
      .attr("height", function(d) { return height - y2(d.value); });

});
       </script>

            <!-- <p>For individual substance graphing data, please see
                <a href="{% url 'dataview:data_summary' use_group.0.id %}">the following individual stats page</a>.</p>
              -->
        {% endfor %}
  {% else %}
    <h3>No Usages to Report!</h3>
  {% endif %}

{% endblock main_page_content %}

{% block default_trailer %}
{% endblock default_trailer %}

dataview/templates/dataview/data_summary.html
{% extends 'home/lasttime_head.html' %}
{% block main_page_content %}
  <h2>{{ sub_name }}</h2>

   <div class="graphing">

    <table summary="Total Administration Data">
      <tr>
          <td>Total Administrations:</td>
          <td>{{ usage_count }}</td>
          <td>Total Administered:</td>
          <td>{{ usage_total }}{{ sub_dosage_units }}</td>
      </tr>
      <tr>
          <td>Average Administered:</td>
          <td>{{ usage_average }}</td>
          <td>Average Span Between Administrations:</td>
          <td>{{ average_span }}</td>
      </tr>
      <tr>
          <td>Highest Dosage:</td>
          <td>{{ usage_high }}{{ sub_dosage_units }}</td>
          <td>Lowest Dosage:</td>
          <td>{{ usage_low }}{{ sub_dosage_units }}</td>
      </tr>
      <tr>
          <td>Longest Span Between Intervals:</td>
          <td>{{ longest_span }}</td>
          <td>Shortest Span Between Intervals:</td>
          <td>{{ shortest_span }}</td>
      </tr>
    </table>

    <h3>Applicable Administrations Listing</h3>

    <h4>Administration Time and Dosage</h4>

    {% if usages %}
     <ol>
       {% for use in usages %}
        <li>{{ use.timestamp }}: {{ use.dosage }}{{ sub_dosage_units }}</li>
       {% endfor %}
     </ol>

     <p><a href="{% url 'dataview:halflife' sub_id %}">See half-life data</a>

     <p><form action="{% url 'dataview:constrained_summary' sub_id %}" method="post">
       {% csrf_token %}
       <input type="submit" value="Constrain dosage graph to per-diem" />
     </form>

     <!-- dosage graph -->
     <div class="dose_chart"></div>
     <script src="http://d3js.org/d3.v3.min.js" type="text/javascript"></script>
     <script type="text/javascript">
        let json_src = '{% url 'dataview:dump_dose_graph_data' sub_id %}';

        var margin = {top: 20, right: 20, bottom: 70, left: 40},
        width = 600 - margin.left - margin.right,
        height = 300 - margin.top - margin.bottom;

        var x = d3.scale.ordinal().rangeRoundBands([0, width], .05);
        var y = d3.scale.linear().range([height, 0]);

        var xAxis = d3.svg.axis()
            .scale(x)
            .orient("bottom")
            .ticks(5);

        var yAxis = d3.svg.axis()
            .scale(y)
            .orient("left")
            .ticks(10);

        var svg = d3.select("body").append("svg")
            .attr("width", width + margin.left + margin.right)
            .attr("height", height + margin.top + margin.bottom)
          .append("g")
            .attr("transform",
                  "translate(" + margin.left + "," + margin.top + ")");

        d3.json(json_src, function(error, data) {
          var ouah = []
          var ouah2 = []
          var ouah3 = []
          for (var cntr = 0; cntr < data.dosages.length; cntr++) {
            ouah[cntr] = {}
            ouah2[cntr] = (cntr + 1);
            ouah3[cntr] = data.dosages[cntr];
            ouah[cntr].date = ouah2[cntr]
            ouah[cntr].value = ouah3[cntr]
          }

          console.log(ouah);

          ouah.forEach(function(d) {
              d.date = d.date;
              d.value = +d.value;
          });

          x.domain(ouah.map(function(d) { return d.date; }));
          y.domain([0, d3.max(ouah3)]);

          svg.append("g")
              .attr("class", "x axis")
              .attr("transform", "translate(0," + height + ")")
              .call(xAxis)
            .selectAll("text")
              .style("text-anchor", "end")
              .attr("dx", "-.8em")
              .attr("dy", "-.55em")
              .attr("transform", "rotate(-90)" );

          svg.append("g")
              .attr("class", "y axis")
              .call(yAxis)
            .append("text")
              .attr("transform", "rotate(-90)")
              .attr("y", 6)
              .attr("dy", ".71em")
              .style("text-anchor", "end")
              .text("Dosage in {{ sub_dosage_units }}");

          svg.selectAll("bar")
              .data(ouah)
            .enter().append("rect")
              .style("fill", "steelblue")
              .attr("x", function(d) { return x(d.date); })
              .attr("width", x.rangeBand())
              .attr("y", function(d) { return y(d.value); })
              .attr("height", function(d) { return height - y(d.value); });

        });

       </script>

    {% else %}

     <p>No administrations have been listed.</p>

    {% endif %}

    <h4>Time Between Subsequent Administrations</h4>

    <p><b>NOTE</b>:  Time span #1 is the duration between administration #1
       &amp; #2, span #2 is between administration #2 &amp; #3, etc ad
       infinitum.

    {% if timespans %}

     <p></p>
     <ol>
       {% for span in timespans %}
         <li>{{ span }}</li>
       {% endfor %}
     </ol>

     <!-- between dosage interval graph -->
     <div class="interval_chart"></div>
     <script src="http://d3js.org/d3.v3.min.js" type="text/javascript"></script>
     <script type="text/javascript">
let json_src2 = '{% url 'dataview:dump_interval_graph_data' sub_id %}';

var margin = {top: 20, right: 20, bottom: 70, left: 40},
    width = 600 - margin.left - margin.right,
    height = 300 - margin.top - margin.bottom;

var x2 = d3.scale.ordinal().rangeRoundBands([0, width], .05);
var y2 = d3.scale.linear().range([height, 0]);

var xAxis2 = d3.svg.axis()
    .scale(x2)
    .orient("bottom")
    .ticks(10);

var yAxis2 = d3.svg.axis()
    .scale(y2)
    .orient("left")
    .ticks(10);

var svg2 = d3.select("body").append("svg")
    .attr("width", width + margin.left + margin.right)
    .attr("height", height + margin.top + margin.bottom)
  .append("g")
    .attr("transform",
          "translate(" + margin.left + "," + margin.top + ")");

d3.json(json_src2, function(error, data) {

    var ouah_interval = [];
    for (var cntr = 0; cntr < data.timespans.length; cntr++) {
        ouah_interval[cntr] = {}
        ouah_interval[cntr].num = cntr + 1;
        ouah_interval[cntr].value = data.timespans[cntr];
    };

    ouah_interval.forEach(function(d) {
        d.num = d.num;
        d.value = +d.value;
    });

    //debugging
    //console.log(ouah_interval);

  x2.domain(ouah_interval.map(function(d) { return d.num; }));
  y2.domain([0, d3.max(ouah_interval, function(d) { return d.value; })]);

  svg2.append("g")
      .attr("class", "x axis")
      .attr("transform", "translate(0," + height + ")")
      .call(xAxis2)
    .selectAll("text")
      .style("text-anchor", "end")
      .attr("dx", "-.8em")
      .attr("dy", "-.55em")
      .attr("transform", "rotate(-90)" );

  svg2.append("g")
      .attr("class", "y axis")
      .call(yAxis2)
    .append("text")
      .attr("transform", "rotate(-90)")
      .attr("y2", 6)
      .attr("dy", ".71em")
      .style("text-anchor", "end")
      .text("Timespan in Hours");

  svg2.selectAll("bar")
      .data(ouah_interval)
    .enter().append("rect")
      .style("fill", "steelblue")
      .attr("x", function(d) { return x2(d.num); })
      .attr("width", x2.rangeBand())
      .attr("y", function(d) { return y2(d.value); })
      .attr("height", function(d) { return height - y2(d.value); });

});
       </script>

    {% else %}

     <p>No timespans have been recorded.</p>

    {% endif %}

   </div>

{% endblock main_page_content %}

{% block default_trailer %}
 <!--
  {% if user.is_authenticated %}
   <div class="botnav">
       <a href="{% url 'dataview:halflife' sub_id %}">See half-life data</a>
       <a href="/accounts/logout">Log out</a></div>
  {% else %}
   <div class="botnav">&nbsp;</p></div>
  {% endif %}
 -->
 </body>
</html>
{% endblock default_trailer %}

dataview/templates/dataview/halflife.html
{% extends 'home/lasttime_head.html' %}

{% block main_page_content %}

    <h1>{{ sub }}</h1>

    <h2>Elimination Extrapolation</h2>

    {% if not sub.lipid_solubility %}

      <h3>Lipid Insoluble Metabolite Breakdown Information</h3>

    {% else %}

      <h3>Lipid Soluble Metabolite Breakdown Information</h3>

      <p>Please note that results here should not be used for anything vital, important, or even tangentally
         useful.  The algorithm implemented is <i>very</i> rough around the edges.  Please feel free to see
         the <a href="https://www.mayocliniclabs.com/test-info/drug-book/marijuana.html">Mayo Clinic labs'
         book on THC metabolite testing</a> for more information on the algorithm's basis.</p>

      <p>Based on the last usage date of <i>{{ last_usage }}</i>, your estimated time of return to a negative
         test result baseline from the most common method of testing is <i><b>{{ undetectable_target }}</b></i></p>

    {% endif %}

    <p>Based on the last usage date of <i>{{ last_usage }}</i>, your estimated time of return to pristine bodily
       fluids is <i><b>{{ elimination_target }}</b></i></p>

{% endblock main_page_content %}

dataview/templates/dataview/index.html
{% extends 'home/lasttime_head.html' %}

{% block main_page_content %}
  {% if relevant_subs %}
    <ul>
    {% for sub in relevant_subs %}
        <li><a href="{% url 'dataview:data_summary' sub.id %}">
            {{ sub.common_name }} ({{ sub.sci_name }})
        </a></li>
    {% endfor %}
    </ul>
  {% else %}
    <h3>No relevant records are available.</h3>
  {% endif %}
{% endblock main_page_content %}
{% block default_trailer %}
     <div class="botnav">
         <a href="{% url 'dataview:sclasses' %}">See class-based breakdowns</a>
         <a href="/accounts/logout">Log out</a></div>
     </div>
  </body>
</html>
{% endblock default_trailer %}

dataview/templates/dataview/sclasses.html
{% extends 'home/lasttime_head.html' %}

{% block main_page_content %}
  <h2>See Detailed Stats per Substance Class</h2>

  {% if classes %}
    <form action="{% url 'dataview:sclasses' %}" method="post">

      {% csrf_token %}

      {% for class in classes %}
        <br><input type="radio" name="class_destination" value="{{ class.id }}">{{ class.name }}</input>
      {% endfor %}

      <br><input type="submit" value="Go!" />

    </form>
  {% else %}
    <h3>No Classes to Display!</h3>
  {% endif %}
{% endblock main_page_content %}